{% set version = '2.0-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wmtsa
  version: {{ version|replace("-", "_") }}

source:
  fn: wmtsa_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/wmtsa_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/wmtsa/wmtsa_{{ version }}.tar.gz
  sha256: 4632cc20e189a7b99e31f8b1ff51aca927989332caeba38e222edcf2f33483e0

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1004
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-ifultools >=2.0_0
    - r-splus2r >=1.2_0
  run:
    - r-base
    - r-mass
    - r-ifultools >=2.0_0
    - r-splus2r >=1.2_0

test:
  commands:
    - $R -e "library('wmtsa')"           # [not win]
    - "\"%R%\" -e \"library('wmtsa')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=wmtsa
  license: GPL-2
  summary: Software to book Wavelet Methods for Time Series Analysis, Donald B. Percival and
    Andrew T. Walden, Cambridge University Press, 2000.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
