travis:
  secure:
    BINSTAR_TOKEN: d12Dh1Y0Jzxm4Y6T8PVeQpDdZ4JPeFMqT/dHzwo/iur5C2uEB1x4YxNGfobwzAhwSm/gJ+Wt1t6Cr6U54dOqjDvwCJBnlIYY7bYAZpWZxQE9pROvmuRBLXYOo/79LySThn3xibE0GZWly5HPIuLPbZ8wga7e8mWKkVpynaDdrjn/ahPsk6m4H3cev8SR2NGZSjlQjFL3m0D7lERqKo8dYsOuIBqr93lhhHIvcwod0Uk3kVb3EVbU8lkHNX+sRAOblebHJC2Z2uMWzqhM6097BqQGg3+2RAUD1rLz3oZ7cDq6D05F+yKSRZX+xnfglFIVi2mytKS51VYWWVhrjQ0gHSpQD/EGDNmbfj9BQF7DBhlotkzskSvh1n6f+mJj9cjHjPGvsgNocZ/MwG4Pmmwth/zArTL+ICLDjtOODoQBUxbM6Ixk3ibaO5SpE/r2PaM4m6eG1di5h6aQoEETe6PP3HtbG8eNp8kiYNNrPnaDZv8RAiXG36194xR+cxVZkGc1ZS7IDyE7H7rlEOekId5ZoxDGDgz/yUQ6HhGpn8H9J1dzPUggnOSe98PwW9NLee8PQXeTQ9S5xTdMBPngZJ/umcDEGLLajRTy/QqBWJ7ei9gpFabb78kacuqxfIHgFUpz6WQvFCHTPW1s57S4Xc5tQBUGtJazkQJOJIHADGks4To=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: false
