appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: YBpzrJ4SXdXLTA5Nkp+RLt739BmkZQn8BUQN1hCeQZpoOo9GO+9vkViGOGn4M8bNcgvZQXwqJuY91dEsBYq3nIvP5b5Lg+psTVTvxZRpPaL7oYud8hAS55o+jVea3smto4ECaT1YNNC5teakBJ0mK+iYnwiyCHTVOXmHcicCvoqxODT7TbpCJ5GqJyBA02vnIVSKnvNShFLI1CjTTyoQTr7bWTbCXToF0969k/zilkwT4v1KnzgcG5cI9gQ7gUjgNPf1E5wmJ19TYtze6EYZa9I8vAJjoScUBNv/YB1GIObNauK/O6B1kxdVjLtJH+RIuS4KruaUql7zAQq37mMe/7X4r9wfZHHxLFM78IvLR+xtSj90UAKXyKdG3VUSsy4q8PZx/1o8Twb3Dm85k4s4OZ9BnwQKo9JAt8zRL8S8Vdd0prnWSuYjcCdcSoNB3BQBQIXQovGJX0GQ9Q3YAiNdeGyHlyfjIINs/tHfcSMGC2jG3lIxKKY6J112P7b700RzFQuelRoe/DP9SMXWOalkFRV6+T60E6B5iFQuEzy6lXC5EUXUrI/FkhCLdlWB9ifewabqz/FTj4Rtv832Qin0SpKVp/ZDt33NM/YuTeXNYWPTqwv0+6RWQi/sxxygbk1RVDZ0MhMDs8GvnUkUbCgssmxEs6qv1lqnF/qHnKA1BwA=}
bot:
  automerge: true
